import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Image from 'next/image'
import './globals.css'

const display = localFont({
  src: [
    { path: './fonts/MatterXHLight.otf', weight: '300', style: 'normal' },
    { path: './fonts/MatterXHRegular.otf', weight: '400', style: 'normal' },
    { path: './fonts/MatterXHMedium.ttf', weight: '500', style: 'normal' },
  ],
  variable: '--font-display',
})

const body = localFont({
  src: [
    { path: './fonts/MatterSemiMonoRegular.otf', weight: '400', style: 'normal' },
    { path: './fonts/MatterSemiMonoMedium.otf', weight: '500', style: 'normal' },
  ],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <header className="flex gap-6 border-b border-gray-200 py-3 sm:px-3 lg:px-4">
          <Image
            className="dark:invert"
            src="/logo.png"
            alt="OCF logo"
            width={100}
            height={20}
            priority
          />
          <div className="flex flex-col items-center gap-6 text-center sm:items-start sm:text-left">
            <h1 className="max-w-xs text-3xl leading-10 font-semibold tracking-tight text-black dark:text-zinc-50">
              Hexatron
            </h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
